webapp/config/routes.rb
class FeatureChatbotConstraint
  def matches?(request)
    u = User.current_user_through_cookies(request.cookie_jar)
    if u.nil?
      Feature.chatbot_enabled?
    else
      Feature.chatbot_enabled? && u.chatbot_enabled
    end
  end
end


Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'backend/invitations', registrations: 'registrations'
  }

  namespace :backend do
    resources :users, only: [:index, :destroy] do
      member do
        get :confirm_destroy
        get :reinvite
        post :toggle_quota_enabled
        post :toggle_chatbot_enabled
      end
      post :impersonate, on: :member
    end
    get 'dashboard', to: 'dashboard#index'
  end

  resource :profile, only: [:show, :edit, :update, :destroy] do
    get :confirm_destroy
    post :stop_impersonating, on: :collection
  end

  resources :chatbots, only: [:index, :show], constraints: FeatureChatbotConstraint.new do
    collection do
      get :search
    end
    member do
      get :reset
    end
    resources :chat_statements, only: [:index, :create] do
      collection do
        post :user_action
      end
    end
  end

  namespace :play do
    resource :selection, only: [:edit, :update] do
      collection do
        get :search
      end
    end
  end
  get  '/play', to: 'play#index'
  post '/play', to: 'play#interpret'
  get  '/play/reset', to: 'play#reset'

  scope '/agents' do
    resources :favorites, only: [:create, :destroy]
    resources :users, path: '', only: [] do
      resources :agents, path: '', except: [:index] do
        member do
          get :confirm_destroy
          get :confirm_transfer_ownership
          post :transfer_ownership
          post :duplicate
          get :generate_token
          get :interpret, to: 'console#interpret'
          get :full_export, to: 'agents_exports#full_export'
          get :agents_selection, to: 'agents_selection#index'
        end

        resources :memberships, only: [:index, :new, :create, :update, :destroy] do
          get :confirm_destroy
        end

        resources :dependencies, only: [:new, :create, :destroy] do
          get :confirm_destroy
          collection do
            get :successors_graph
            get :predecessors_graph
          end
        end

        resource :readme, except: [:show] do
          get :confirm_destroy
        end

        resources :interpretations, path: 'interpretations' do
          member do
            post :move_to_agent
          end

          get :select_new_locale
          post :add_locale
          get :confirm_destroy

          collection do
            post :update_positions
          end

          resources :aliased_interpretations, only: :index

          resources :formulations, only: [:show, :create, :edit, :update, :destroy] do
            member do
              get :show_detailed
              post :update_locale
            end
            collection do
              post :update_positions
            end
          end
        end

        resources :entities_lists do
          member do
            post :move_to_agent
            get :export, to: 'entities_lists_exports#show'
          end

          get :confirm_destroy

          collection do
            post :update_positions
          end

          resources :aliased_interpretations, only: :index

          resources :entities, only: [:show, :create, :edit, :update, :destroy] do
            member do
              get :show_detailed
            end
            collection do
              post :update_positions
              get :new_import
              post :create_import
            end
          end
        end

        resources :agent_regression_checks, only: [:create, :update, :destroy] do
          collection do
            post :run
            post :update_positions
          end
        end

        resources :bots, except: [:show], constraints: FeatureChatbotConstraint.new do
          member do
            get :confirm_destroy
          end
          collection do
            get :ping
          end
        end

      end
    end
  end

  get 'agents', to: 'agents#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    # disable ip_spoofing, because it does not support multiple reverse proxy with different configuration (HTTP_X_REAL_IP != HTTP_X_FORWARDED_FOR)
    Sidekiq::Web.use(Rack::Protection, except: :ip_spoofing)

    mount Sidekiq::Web => '/backend/jobs'
  end

  # API with versioning
  namespace :api do
    namespace :v1 do
      scope '/agents' do
        get '/:ownername/:agentname/interpret', to: 'nlp#interpret'
      end
      get '/ping', to: 'ping#ping'
      resources 'chat_sessions', only: [:update], constraints: FeatureChatbotConstraint.new do
        resources 'statements', only: [:create], controller: 'chat_statements'
      end
    end
  end

  # API internal without versioning
  namespace :api_internal do
    get '/packages',              to: 'packages#index'
    get '/packages/:id',          to: 'packages#show'
    post '/packages/:id/updated', to: 'packages#updated'
  end

  get 'style-guide(/:page_id)', to: "style_guide#page"

  unless File.exist? File.join(Rails.root, 'public', 'index.html')
    devise_scope :user do
      unauthenticated :user do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
      authenticate :user do
        root to: 'agents#index', as: :authenticated_root
      end
    end
  end

  get "connexion_state" => "application#connexion_state"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_error", via: :all
end

webapp/app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

webapp/app/views/layouts/_matomo.html.erb
<script>
  var _paq = window._paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="<%= ENV['VIKYAPP_MATOMO_TRACKER_URL'] %>";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '<%= ENV['VIKYAPP_MATOMO_SITE_ID'] %>']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src='//cdn.matomo.cloud/vikyai.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
  })();
  (function() {
    var previousPageUrl = null;
    addEventListener('turbolinks:load', function(event) {
      if (previousPageUrl) {
        _paq.push(['setReferrerUrl', previousPageUrl]);
        _paq.push(['setCustomUrl', window.location.href]);
        _paq.push(['setDocumentTitle', document.title]);
        if (event.data && event.data.timing) {
          _paq.push(['setGenerationTimeMs', event.data.timing.visitEnd - event.data.timing.visitStart]);
        }
        _paq.push(['trackPageView']);
      }
      previousPageUrl = window.location.href;
    });
  })();
</script>

webapp/app/views/layouts/_nav.html.erb
<nav class="h-nav">

  <div class="h-nav__header">
    <a href="/" data-turbolinks="false">
      <span class="logo"><%= logo_on_white %></span>
    </a>
  </div>

  <div class="h-nav__content">
    <ul>
      <li>
        <a href="<%= agents_path %>" <% if ['agents', 'interpretations', 'entities_lists', 'bots'].include? controller_path %>class="current"<% end %>>
          <%= t('views.nav.agents') %>
        </a>
      </li>
      <li>
        <a href="/play" <% if ['play'].include? controller_path %>class="current"<% end %>>
          <%= t('views.nav.play') %>
        </a>
      </li>
      <% if Feature.chatbot_enabled? && current_user.chatbot_enabled? %>
        <li>
          <a href="<%= chatbots_path %>" <% if ['chatbots'].include? controller_path %>class="current"<% end %>>
            <%= t('views.nav.chatbots') %>
          </a>
        </li>
      <% end %>

      <% if current_user.admin %>
        <li class="more">
          <div class="dropdown">
            <a href="#" class="dropdown__trigger">
              <span class="icon">
                <%= icon_dots %>
              </span>
            </a>
            <div class="dropdown__content dropdown__content--hidden">
              <ul>
                <li>
                  <a href="<%= backend_dashboard_path %>"
                     <% if controller_path.include?('backend/dashboard') %>class="current"<% end %>>
                    <%= t('views.nav.backend.dashboard') %>
                  </a>
                </li>
                <li>
                  <a href="<%= backend_users_path %>"
                    <% if ['backend/users','backend/invitations'].include? controller_path %>
                      class="current"
                    <% end %>>
                    <%= t('views.nav.backend.users') %>
                  </a>
                </li>
                <li class="separator">
                  <a href="/style-guide/icon" data-turbolinks="false" target="_blank">
                    <%= t('views.nav.backend.style_guide') %>
                    <span class="icon icon--x-small"><%= icon_open_in_new %></span>
                  </a>
                </li>
                <li>
                  <a href="/backend/jobs/" data-turbolinks="false" target="_blank">
                    <%= t('views.nav.backend.sidekiq_ui') %>
                    <span class="icon icon--x-small"><%= icon_open_in_new %></span>
                  </a>
                </li>
                <li>
                  <a href="/rails/mailers/" data-turbolinks="false" target="_blank">
                    <%= t('views.nav.backend.mailer_test') %>
                    <span class="icon icon--x-small"><%= icon_open_in_new %></span>
                  </a>
                </li>
                <% kibana_url = Rails.env.development? ? 'http://localhost:5601/kibana/' : '/kibana/'%>
                <li>
                  <a href="<%= kibana_url %>" data-turbolinks="false" target="_blank">
                    <%= t('views.nav.backend.kibana_ui') %>
                    <span class="icon icon--x-small"><%= icon_open_in_new %></span>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="h-nav__content">
    <ul>
      <li>
        <a href="<%= profile_path %>" <% if controller_path.include?('profile') %>class="current"<% end %>>
          <div class="user">
            <div class="user__avatar user__avatar--small">
              <img src="<%= current_user.image_url(:square) %>">
            </div>
            <div class="user__info">
              <% if current_user.name.blank? %>
                <%= current_user.username %>
              <% else %>
                <%= current_user.name %>
              <% end %>
              <% if current_user != true_user %>
                &nbsp;<span class="badge badge--danger"><%= t('views.nav.switched') %></span>
              <% end %>
            </div>
          </div>
        </a>
      </li>
      <% if current_user != true_user %>
        <li>
          <a href="<%= stop_impersonating_profile_path %>" rel="nofollow" data-method="post">
            <div class="user">
              <div class="user__avatar user__avatar--small">
                <img src="<%= true_user.image_url(:square) %>">
              </div>
              <div class="user__info">
                <%= t('views.nav.comeback') %>
              </div>
            </div>
          </a>
        </li>
      <% end %>
      <li>
        <%= link_to "<span class='icon' title='Logout'>#{icon_logout}</span>".html_safe,
              destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </div>

</nav>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      viky.ai
      <% unless @agent.nil? %>
        - <%= @agent.slug %><% unless @interpretation.nil? %>/<%= @interpretation.interpretation_name %><% end %>
      <% end %>
      <% if controller_path == "profiles" %>
        - <%= t('views.profile.breadcrumb') %>
      <% end %>
      <% if controller_path == "backend/users" %>
        - <%= t('views.backend.breadcrumb.user_management') %>
      <% end %>
    </title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= render 'layouts/favicon' %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Feature.matomo_enabled? %><%= render 'layouts/matomo' %><% end %>
  </head>

  <body data-controller-name="<%= controller_path %>"
        data-controller-action="<%= action_name %>"
        data-current-user="<%= current_user.id %>"
        <% unless @agent.nil? %>
          data-agent-id="<%= @agent.id %>"
        <% end %>
        <% if controller_path == 'entities_lists' && action_name == 'show' %>
          data-entities-list-id="<%= @entities_list.id %>"
        <% end %>
        class="app <% if controller_path.include?('style_guide') %>sg<% end %>">

    <%= render 'layouts/nav' %>

    <div class="app-wrapper">

      <% if content_for?(:left_aside) %>
        <%= yield :left_aside %>
      <% end %>

      <main>
        <%= yield %>

        <% unless notice.nil? %>
          <div class="message message--notice">
            <div class="message__content">
              <% if notice.is_a?(Hash) %>
                <%= t(notice['i18n_key'], notice['locals'].nil? ? {} : notice['locals'].symbolize_keys) %>
              <% else %>
                <%= notice %>
              <% end %>
            </div>
            <div class="message__action">
              <a href="#" data-action="message-close"><span class="icon"><%= icon_close %></span></a>
            </div>
          </div>
        <% end %>

        <% unless alert.nil? %>
          <div class="message message--alert">
            <div class="message__content">
              <% if alert.is_a?(Hash) %>
                <%= t(alert['i18n_key'], alert['locals'].nil? ? {} : alert['locals'].symbolize_keys) %>
              <% else %>
                <%= alert %>
              <% end %>
            </div>
            <div class="message__action">
              <a href="#" data-action="message-close"><span class="icon"><%= icon_close %></span></a>
            </div>
          </div>
        <% end %>
      </main>

      <% if content_for?(:right_aside) %>
        <%= yield :right_aside %>
      <% end %>

    </div>
  </body>
</html>

webapp/app/views/layouts/devise.html.erb
<%
  case controller_name
  when "registrations"
    @title = "#{t('views.registrations.new.title')} - viky.ai"
  when "sessions"
    @title = "#{t('views.sessions.new.title')} - viky.ai"
  when "passwords"
    @title = "#{t('views.passwords.new.title')} - viky.ai"
  when "confirmations"
    @title = "#{t('views.confirmations.new.title')} - viky.ai"
  when "unlocks"
    @title = "#{t('views.unlocks.new.title')} - viky.ai"
  else
    @title = "viky.ai"
  end
%>

<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= render 'layouts/favicon' %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Feature.matomo_enabled? %><%= render 'layouts/matomo' %><% end %>
  </head>
  <body>
    <div class="login-wrapper">

      <div class="login-ui-wrapper
                  <% unless resource.errors.empty? %>robot-trouble<% end %>
                  <% unless alert.nil? %>robot-trouble<% end %>
                  <% unless notice.nil? %>robot-happy<% end %>">

        <h1 class="logo-container">
          <a href="/" class="logo logo--x-large" data-turbolinks="false">
            <%= logo_on_white %>
          </a>
        </h1>

        <% unless notice.nil? %>
          <div class="card card--success">
            <div class="card-content">
              <%= notice %>
            </div>
          </div>
        <% end %>

        <% unless alert.nil? %>
          <div class="card card--alert">
            <div class="card-content">
              <%= alert %>
            </div>
          </div>
        <% end %>

        <%= yield %>

        </div>

    </div>
  </body>
</html>

webapp/app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>viky.ai</title>
    <%= csrf_meta_tags %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= render 'layouts/favicon' %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'errors', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'errors', 'data-turbolinks-track': 'reload' %>
    <% if Feature.matomo_enabled? %><%= render 'layouts/matomo' %><% end %>
  </head>

  <body>
    <div class="container">
      <div class="message">
        <div class="message__logo">
          <%= logo_on_white %>
        </div>
        <div class="message__box">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

webapp/app/views/layouts/style_guide.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>viky.ai - Style Guide</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= render 'layouts/favicon' %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'style_guide', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'style_guide', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="app sg">
    <div class="app-wrapper app-wrapper--without-h-nav">
      <aside class="v-nav">
        <div class="v-nav__header">
          <p>
            Style Guide
            <%= logo_on_dark %>
          </p>
        </div>
        <div class="v-nav__content">
          <ul>
            <% @pages.each_with_index do |page, i| %>
              <li>
                <a href="/style-guide/<%= page[:slug] %>"
                   <% if @page[:slug] == page[:slug] %>class="current"<% end %>>
                  <%= page[:name] %>
                </a>
                <% if @page[:slug] == page[:slug] %>
                  <ul class="style-guide" data-turbolinks="false"></ul>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </aside>

      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>