webapp/config/routes.rb
class FeatureChatbotConstraint
  def matches?(request)
    u = User.current_user_through_cookies(request.cookie_jar)
    if u.nil?
      Feature.chatbot_enabled?
    else
      Feature.chatbot_enabled? && u.chatbot_enabled
    end
  end
end


Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'backend/invitations', registrations: 'registrations'
  }

  namespace :backend do
    resources :users, only: [:index, :destroy] do
      member do
        get :confirm_destroy
        get :reinvite
        post :toggle_quota_enabled
        post :toggle_chatbot_enabled
      end
      post :impersonate, on: :member
    end
    get 'dashboard', to: 'dashboard#index'
  end

  resource :profile, only: [:show, :edit, :update, :destroy] do
    get :confirm_destroy
    post :stop_impersonating, on: :collection
  end

  resources :chatbots, only: [:index, :show], constraints: FeatureChatbotConstraint.new do
    collection do
      get :search
    end
    member do
      get :reset
    end
    resources :chat_statements, only: [:index, :create] do
      collection do
        post :user_action
      end
    end
  end

  namespace :play do
    resource :selection, only: [:edit, :update] do
      collection do
        get :search
      end
    end
  end
  get  '/play', to: 'play#index'
  post '/play', to: 'play#interpret'
  get  '/play/reset', to: 'play#reset'

  scope '/agents' do
    resources :favorites, only: [:create, :destroy]
    resources :users, path: '', only: [] do
      resources :agents, path: '', except: [:index] do
        member do
          get :confirm_destroy
          get :confirm_transfer_ownership
          post :transfer_ownership
          post :duplicate
          get :generate_token
          get :interpret, to: 'console#interpret'
          get :full_export, to: 'agents_exports#full_export'
          get :agents_selection, to: 'agents_selection#index'
        end

        resources :memberships, only: [:index, :new, :create, :update, :destroy] do
          get :confirm_destroy
        end

        resources :dependencies, only: [:new, :create, :destroy] do
          get :confirm_destroy
          collection do
            get :successors_graph
            get :predecessors_graph
          end
        end

        resource :readme, except: [:show] do
          get :confirm_destroy
        end

        resources :interpretations, path: 'interpretations' do
          member do
            post :move_to_agent
          end

          get :select_new_locale
          post :add_locale
          get :confirm_destroy

          collection do
            post :update_positions
          end

          resources :aliased_interpretations, only: :index

          resources :formulations, only: [:show, :create, :edit, :update, :destroy] do
            member do
              get :show_detailed
              post :update_locale
            end
            collection do
              post :update_positions
            end
          end
        end

        resources :entities_lists do
          member do
            post :move_to_agent
            get :export, to: 'entities_lists_exports#show'
          end

          get :confirm_destroy

          collection do
            post :update_positions
          end

          resources :aliased_interpretations, only: :index

          resources :entities, only: [:show, :create, :edit, :update, :destroy] do
            member do
              get :show_detailed
            end
            collection do
              post :update_positions
              get :new_import
              post :create_import
            end
          end
        end

        resources :agent_regression_checks, only: [:create, :update, :destroy] do
          collection do
            post :run
            post :update_positions
          end
        end

        resources :bots, except: [:show], constraints: FeatureChatbotConstraint.new do
          member do
            get :confirm_destroy
          end
          collection do
            get :ping
          end
        end

      end
    end
  end

  get 'agents', to: 'agents#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    # disable ip_spoofing, because it does not support multiple reverse proxy with different configuration (HTTP_X_REAL_IP != HTTP_X_FORWARDED_FOR)
    Sidekiq::Web.use(Rack::Protection, except: :ip_spoofing)

    mount Sidekiq::Web => '/backend/jobs'
  end

  # API with versioning
  namespace :api do
    namespace :v1 do
      scope '/agents' do
        get '/:ownername/:agentname/interpret', to: 'nlp#interpret'
      end
      get '/ping', to: 'ping#ping'
      resources 'chat_sessions', only: [:update], constraints: FeatureChatbotConstraint.new do
        resources 'statements', only: [:create], controller: 'chat_statements'
      end
    end
  end

  # API internal without versioning
  namespace :api_internal do
    get '/packages',              to: 'packages#index'
    get '/packages/:id',          to: 'packages#show'
    post '/packages/:id/updated', to: 'packages#updated'
  end

  get 'style-guide(/:page_id)', to: "style_guide#page"

  unless File.exist? File.join(Rails.root, 'public', 'index.html')
    devise_scope :user do
      unauthenticated :user do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
      authenticate :user do
        root to: 'agents#index', as: :authenticated_root
      end
    end
  end

  get "connexion_state" => "application#connexion_state"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_error", via: :all
end

webapp/app/helpers/formulation_helper.rb
module FormulationHelper

  def rtl?(locale)
    locale == 'ar'
  end

  def interpretation_to_json(interpretation)
    JSON.generate(
      color:  "interpretation-#{interpretation.color}",
      aliasname: interpretation.interpretation_name,
      slug: interpretation.slug,
      formulation_aliasable_id: interpretation.id,
      formulation_aliasable_type: Interpretation.name,
      nature: FormulationAlias.natures.key(FormulationAlias.natures[:type_interpretation])
    )
  end

  def entities_list_to_json(entities_list)
    JSON.generate(
      color:  "entities_list-#{entities_list.color}",
      aliasname: entities_list.listname,
      slug: entities_list.slug,
      formulation_aliasable_id: entities_list.id,
      formulation_aliasable_type: EntitiesList.name,
      nature: FormulationAlias.natures.key(FormulationAlias.natures[:type_entities_list])
    )
  end

  def number_to_json
    JSON.generate({
      color:  "interpretation-black",
      aliasname: t("views.formulations.number").downcase,
      nature: FormulationAlias.natures.key(FormulationAlias.natures[:type_number])
    })
  end

  def regex_to_json
    JSON.generate({
      color: "interpretation-black",
      aliasname: t("views.formulations.regex").downcase,
      nature: FormulationAlias.natures.key(FormulationAlias.natures[:type_regex]),
      reg_exp: ""
    })
  end

  def alias_to_json_href(formulation_alias)
    ERB::Util.url_encode(alias_to_json(formulation_alias))
  end

  def alias_to_json(formulation_alias)
    if formulation_alias.type_number?
      data = {
        color: "interpretation-black",
        aliasname: formulation_alias.aliasname,
        nature: FormulationAlias.natures.key(FormulationAlias.natures[:type_number]),
        is_list: formulation_alias.is_list,
        any_enabled: formulation_alias.any_enabled,
        slug: t("views.formulations.number")
      }
    elsif formulation_alias.type_regex?
      data = {
        color: "interpretation-black",
        aliasname: formulation_alias.aliasname,
        nature: FormulationAlias.natures.key(FormulationAlias.natures[:type_regex]),
        reg_exp: formulation_alias.reg_exp,
        is_list: formulation_alias.is_list,
        any_enabled: formulation_alias.any_enabled,
        slug: t("views.formulations.regex")
      }
    else
      current_aliasable = formulation_alias.formulation_aliasable
      url = nil
      if current_user.can?(:show, current_aliasable.agent)
        if formulation_alias.type_interpretation?
          url = user_agent_interpretation_path(current_aliasable.agent.owner, current_aliasable.agent, current_aliasable)
        elsif formulation_alias.type_entities_list?
          url = user_agent_entities_list_path(current_aliasable.agent.owner, current_aliasable.agent, current_aliasable)
        end
      end
      data = {
        aliasname: formulation_alias.aliasname,
        slug: current_aliasable.slug,
        formulation_aliasable_id: current_aliasable.id,
        is_list: formulation_alias.is_list,
        any_enabled: formulation_alias.any_enabled,
        url: url,
      }
      if formulation_alias.type_interpretation?
        data[:color] = "interpretation-#{current_aliasable.color}"
        data[:formulation_aliasable_type] = Interpretation.name
        data[:nature] = FormulationAlias.natures.key(FormulationAlias.natures[:type_interpretation])
      end
      if formulation_alias.type_entities_list?
        data[:color] = "entities_list-#{current_aliasable.color}"
        data[:formulation_aliasable_type] = EntitiesList.name
        data[:nature] = FormulationAlias.natures.key(FormulationAlias.natures[:type_entities_list])
      end
    end
    data[:id] = formulation_alias.id unless formulation_alias.id.nil?

    unless formulation_alias.errors[:aliasname].empty?
      data[:aliasname_errors] = display_errors(formulation_alias, :aliasname)
    end

    unless formulation_alias.errors[:reg_exp].empty?
      data[:regex_errors] = display_errors(formulation_alias, :reg_exp)
    end

    unless formulation_alias.errors[:base].empty?
      data[:base_errors] = display_errors(formulation_alias, :base)
    end

    JSON.generate(data)
  end


  def display_expression_for_trix(formulation)
    expression = formulation.expression
    return expression if formulation.formulation_aliases.empty?

    ordered_aliases = formulation.formulation_aliases
                        .reject { |ialias| ialias._destroy }
                        .sort_by { |ialias| ialias.position_start }
    result = []
    expression.split('').each_with_index do |character, index|
      formulation_alias = ordered_aliases.first
      if formulation_alias.nil? || index < formulation_alias.position_start
        result << character
      end
      if !formulation_alias.nil? && index == formulation_alias.position_end - 1
        text = expression[formulation_alias.position_start..formulation_alias.position_end-1]
        result << "<a href=\"#{alias_to_json_href(formulation_alias)}\">#{text}</a>"
        ordered_aliases = ordered_aliases.drop(1)
      end
    end
    result.join('')
  end


  def display_expression(formulation)
    expression = formulation.expression

    result = []

    if formulation.formulation_aliases.count == 0
      result << expression
    else
      ordered_aliases = formulation.formulation_aliases.order(position_start: :asc)

      result << "<span class='formulation-resume'>"
      expression.split('').each_with_index do |character, index|
        formulation_alias = ordered_aliases.first
        if formulation_alias.nil? || index < formulation_alias.position_start
          result << character
        end
        if !formulation_alias.nil? && index == formulation_alias.position_end - 1
          if formulation_alias.type_number?
            color = "black"
            title = "Number"
          elsif formulation_alias.type_regex?
            color = "black"
            title = "Regex: #{formulation_alias.reg_exp}"
          else
            title = formulation_alias.formulation_aliasable.slug
            color = formulation_alias.formulation_aliasable.color
          end
          css_class = "formulation-resume__alias-#{color}"
          text = expression[formulation_alias.position_start..formulation_alias.position_end-1]
          result << "<span class='#{css_class}' title='#{title}'>#{text}</span>"
          ordered_aliases = ordered_aliases.drop(1)
        end
      end
      result << "</span>"
    end

    result << "&nbsp;"
    result << "&nbsp;"

    if formulation.keep_order
      result << "&nbsp;"
      result << "<span class='badge' title='#{t("views.formulations.keep_order_description")}'>"
      result << t('activerecord.attributes.formulation.keep_order')
      result << "</span>"
    end

    result << "&nbsp;"
    result << "<span class='badge' title='#{t("views.formulations.proximity.description.#{formulation.proximity}")}'>"
    result << t("views.formulations.proximity.#{formulation.proximity}")
    result << "</span>"

    if formulation.auto_solution_enabled
      result << "&nbsp;"
      result << " <span class='badge' title='#{t("views.formulations.auto_solution_description")}'>"
      result << t('activerecord.attributes.formulation.auto_solution_enabled')
      result << "</span>"
    end

    result.join('').html_safe
  end

end

webapp/app/views/formulations/_blankslate_start.html.erb
<div id="blankslate-start"
     <% unless interpretation.formulations_with_local(@current_locale).empty? %>style="display:none;"<% end %>>

  <div class="card">
    <div class="card-content">
      <div class="blankslate">
        <div class="blankslate__illustration">
          <img src='<%= image_path "robot-idle.png" %>'
               srcset='<%= image_path "robot-idle.png" %> 1x,
                       <%= image_path "robot-idle@2x.png" %> 2x' />
        </div>
        <div class="blankslate__content">
          <% if current_locale == Locales::ANY %>
            <% language = t('locales.no_locale') %>
          <% else %>
            <% language = current_locale %>
          <% end %>
          <p>
            <%= t('views.formulations.blankslate.no_expression', language: language) %>
            <% if current_user.can? :edit, agent %>
              <br /><%= t('views.formulations.blankslate.start') %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>

</div>

webapp/app/views/formulations/_create_failed.js.erb
$("#formulations-form").replaceWith("<%= escape_javascript(@html_form) %>");
App.CodeEditor.buildJavaScriptEditor($("#solution__new_formulation")[0]);

webapp/app/views/formulations/_destroy_failed.js.erb
App.Message.notice("<%= escape_javascript(t('views.formulations.delete_failed')) %>");

webapp/app/views/formulations/_destroy_succeed.js.erb
App.CardListHelper.removeFromList("#formulation-<%= @formulation.id %>")

setTimeout(function(){
  App.CardListHelper.updateBlankslates();
  App.CardListHelper.updateDraggable();
}, 200);

App.FormulationsList.decrementTabBadge();

webapp/app/views/formulations/_edit.html.erb
<div class="card-list__item__draggable"></div>

<%= form_with(model: [formulation.interpretation.agent.owner, formulation.interpretation.agent, formulation.interpretation, formulation], class: 'formulations-form') do |f| %>

  <% formulation.formulation_aliases.select { |ialias| ialias._destroy }.each do |ialias| %>
    <input type="hidden" name="formulation[formulation_aliases_attributes][][id]" value="<%= ialias.id %>" />
    <input type="hidden" name="formulation[formulation_aliases_attributes][][position_start]"                value="" />
    <input type="hidden" name="formulation[formulation_aliases_attributes][][position_end]"                  value="" />
    <input type="hidden" name="formulation[formulation_aliases_attributes][][formulation_aliasable_id]"   value="" />
    <input type="hidden" name="formulation[formulation_aliases_attributes][][formulation_aliasable_type]" value="" />
    <input type="hidden" name="formulation[formulation_aliases_attributes][][aliasname]"                     value="" />
    <input type="hidden" name="formulation[formulation_aliases_attributes][][nature]"                        value="" />
    <input type="hidden" name="formulation[formulation_aliases_attributes][][_destroy]"                      value="1" />
  <% end %>
  <div class="field formulations-form__formulation">
    <div class="control trix-control">
      <div class="trix-control__option <% if rtl?(formulation.locale) %>trix-control__option--rtl<% end %>">
        <div class="trix-control__option__child"
             title="<%= t("views.formulations.keep_order_description") %>">
          <%= f.check_box :keep_order, id: "keep_order__#{formulation.id}" %>
          <%= f.label :keep_order, for: "keep_order__#{formulation.id}" %>
        </div>
        <div class="trix-control__option__child">
          <%= f.hidden_field :proximity, id: "proximity__#{formulation.id}" %>
          <div class="dropdown">
            <div class="dropdown__trigger">
              <button class="btn btn--outline btn--small">
                <span class="btn__label">
                  <%= t("views.formulations.proximity.#{formulation.proximity}") %>
                </span>
                <span class="icon icon--x-small">
                  <%= icon_arrow_down %>
                </span>
              </button>
            </div>
            <div class="dropdown__content dropdown__content--hidden">
              <ul>
                <% Formulation.proximities.each_key do |proximity| %>
                  <li>
                    <a href="#"
                       <% if proximity == formulation.proximity.to_s %>class="current"<% end %>
                       data-behavior="populate-input, replace-trigger-label"
                       data-input-selector="#proximity__<%= formulation.id %>"
                       data-input-value="<%= proximity %>"
                       data-replace-selector=".btn__label"
                       data-replace-with="<%= t("views.formulations.proximity.#{proximity}") %>">
                      <div class="dropdown__content__item-title">
                        <%= t("views.formulations.proximity.#{proximity}") %>
                      </div>
                      <div class="dropdown__content__item-description">
                        <%= t("views.formulations.proximity.description.#{proximity}") %>
                      </div>
                    </a>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div class="trix-control__option__child"
             title="<%= t("views.formulations.auto_solution_description") %>">
          <%= f.check_box :auto_solution_enabled, id: "auto_solution_enabled__#{formulation.id}" %>
          <%= f.label :auto_solution_enabled, for: "auto_solution_enabled__#{formulation.id}" %>
        </div>
      </div>
      <textarea name="formulation[expression]" style="display:none;"
        id="<%= "expression-#{formulation.id}" %>"><%= display_expression_for_trix(formulation) %></textarea>
      <trix-editor <% if rtl?(formulation.locale) %>dir="rtl"<% end %>
        input="<%= "expression-#{formulation.id}" %>"
        placeholder="<%= t('views.formulations.new.placeholder') %>"></trix-editor>
    </div>
    <%= display_errors(formulation, :expression) %>
    <%= display_errors(formulation, :locale) %>
    <%= display_errors(formulation, :keep_order) %>
    <%= display_errors(formulation, :proximity) %>
  </div>

  <div class="aliases <% if rtl?(formulation.locale) %>aliases--rtl<% end %> formulations-form__summary" style="display: none;"></div>

  <div class="formulations-form__aliases-errors">
    <%= display_errors(formulation, :base) %>
  </div>

  <div class="field field--for-solution formulations-form__solution"
      <% if formulation.auto_solution_enabled %>style="display:none;"<% end %>>
    <div class="control">
      <span class="solution-label">
        <%= t('views.formulations.solution_label') %>
      </span>
      <%= f.text_area :solution, id: "solution__#{formulation.id}", maxlength: '6000', spellcheck: 'false' %>
    </div>
    <%= display_errors(formulation, :solution) %>
  </div>

  <div class="field field--submit">
    <div class="control">
      <%= f.button t('views.formulations.index.update_btn').html_safe, class: 'btn btn--primary',
            data: { disable_with: "<span class='icon icon--small icon--spin'>#{icon_loading}</span> #{t('loading')}" } %>
      <%= link_to t('views.formulations.index.cancel_btn'),
            user_agent_interpretation_formulation_path(
              formulation.interpretation.agent.owner,
              formulation.interpretation.agent,
              formulation.interpretation,
              formulation
            ),
            remote: true,
            class: 'btn btn--plain',
            data: { disable_with: "<span class='icon icon--small icon--spin'>#{icon_loading}</span>" } %>
    </div>
  </div>
  <div class="field formulations-form__delete">
    <div class="control">
      <%= link_to t('views.formulations.index.delete_btn'),
                  user_agent_interpretation_formulation_path(
                      formulation.interpretation.agent.owner,
                      formulation.interpretation.agent,
                      formulation.interpretation,
                      formulation
                  ),
                  method: :delete,
                  remote: true,
                  class: 'btn btn--small btn--outline btn--destructive',
                  data: { disable_with: "<span class='icon icon--small icon--spin'>#{icon_loading}</span>" } %>
    </div>
  </div>
<% end %>

webapp/app/views/formulations/_edit.js.erb
App.CardListHelper.updateItem("#formulation-<%= @formulation.id %>", "<%= escape_javascript(@form) %>");
App.CardListHelper.updateDraggable();
App.CodeEditor.buildJavaScriptEditor($("#solution__<%= @formulation.id %>")[0]);

$("body").trigger('formulations:edit:complete');

webapp/app/views/formulations/_form.html.erb
<%= form_with model: [agent.owner, agent, interpretation, formulation],
              id: 'formulations-form',
              class: 'formulations-form' do |f| %>

  <%= f.hidden_field :locale, value: @current_locale %>
  <%= f.hidden_field :proximity, id: "proximity__new_formulation", value: formulation.proximity %>

  <div class="field formulations-form__formulation">
    <div class="control trix-control">
      <div class="trix-control__option  <% if rtl?(@current_locale) %>trix-control__option--rtl<% end %>">
        <div class="trix-control__option__child"
             title="<%= t("views.formulations.keep_order_description") %>">
          <%= f.check_box :keep_order, id: "keep_order__new_formulation" %>
          <%= f.label :keep_order, for: "keep_order__new_formulation" %>
        </div>
        <div class="trix-control__option__child">
          <div class="dropdown">
            <div class="dropdown__trigger">
              <button class="btn btn--outline btn--small" type="button">
                <span class="btn__label">
                  <%= t("views.formulations.proximity.#{formulation.proximity}") %>
                </span>
                <span class="icon icon--x-small">
                  <%= icon_arrow_down %>
                </span>
              </button>
            </div>
            <div class="dropdown__content dropdown__content--hidden">
              <ul>
                <% Formulation.proximities.each_key do |proximity| %>
                  <li>
                    <% label = t("expression.proximity.#{proximity}") %>
                    <a href="#"
                       <% if proximity == formulation.proximity.to_s %>class="current"<% end %>
                       data-behavior="populate-input, replace-trigger-label"
                       data-input-selector="#proximity__new_formulation"
                       data-input-value="<%= proximity %>"
                       data-replace-selector=".btn__label"
                       data-replace-with="<%= t("views.formulations.proximity.#{proximity}") %>">
                      <div class="dropdown__content__item-title">
                        <%= t("views.formulations.proximity.#{proximity}") %>
                      </div>
                      <div class="dropdown__content__item-description">
                        <%= t("views.formulations.proximity.description.#{proximity}") %>
                      </div>
                    </a>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div class="trix-control__option__child"
             title="<%= t("views.formulations.auto_solution_description") %>">
          <%= f.check_box :auto_solution_enabled, id: "auto_solution_enabled__new_formulation" %>
          <%= f.label :auto_solution_enabled, for: "auto_solution_enabled__new_formulation" %>
        </div>
      </div>
      <textarea name="formulation[expression]" style="display:none;"
        id="expression-new"><%= display_expression_for_trix(formulation) %></textarea>
      <trix-editor autofocus <% if rtl?(@current_locale) %>dir="rtl"<% end %>
        input="expression-new"
        placeholder="<%= t('views.formulations.new.placeholder') %>"></trix-editor>
    </div>
    <%= display_errors(formulation, :expression) %>
    <%= display_errors(formulation, :locale) %>
    <%= display_errors(formulation, :keep_order) %>
    <%= display_errors(formulation, :proximity) %>
    <%= display_errors(formulation, :quota) %>
  </div>

  <div class="aliases <% if rtl?(@current_locale) %>aliases--rtl<% end %> formulations-form__summary" style="display:none;"></div>

  <div class="formulations-form__aliases-errors">
    <%= display_errors(formulation, :base) %>
  </div>

  <div class="field field--for-solution formulations-form__solution" style="display:none;">
    <div class="control">
      <span class="solution-label">Solution</span>
      <%= f.text_area :solution, id: "solution__new_formulation", maxlength: '6000', spellcheck: 'false' %>
    </div>
    <%= display_errors(formulation, :solution) %>
  </div>

  <div class="field field--submit">
    <div class="control">
      <%= f.button t('views.formulations.new.btn'), class: 'btn btn--primary formulations-form__submit',
                   data: {
                       disable_with: "<span class='icon icon--small icon--spin'>#{icon_loading}</span> #{t('loading')}".html_safe
                   } %>
    </div>
  </div>
<% end %>

webapp/app/views/formulations/_formulations_list.html.erb
<ul id="formulations-list" class="card-list"
    data-behavior="sortable"
    data-update-positions-path="<%= update_positions_user_agent_interpretation_formulations_path(@agent.owner, @agent, @interpretation) %>"
    data-key='ids'
    data-group="formulations">
  <%= render partial: '/formulations/formulation',
             collection: @interpretation.formulations_with_local(@current_locale).order(position: :desc, created_at: :desc),
             locals: {
                 can_edit: current_user.can?(:edit, @agent),
                 interpretation: @interpretation,
                 agent: @agent,
                 owner: @agent.owner
             } %>
</ul>

webapp/app/views/formulations/_index.html.erb
<div class="card">
  <div class="tabs <% unless current_user.can? :edit, @agent %>tabs--empty<% end %>">
    <ul>
      <% for agent_locale in @agent.ordered_locales %>
        <% if agent_locale == Locales::ANY %>
          <% link_name = t('locales.no_locale') %>
        <% else %>
          <% link_name = agent_locale %>
        <% end %>
        <li data-locale="<%= agent_locale %>"
          <% if @current_locale != agent_locale %>class="js-draggable-locale"<% end %>>
          <a href="<%= user_agent_interpretation_path(@agent.owner, @agent, @interpretation, locale: agent_locale) %>"
             <% if @current_locale == agent_locale %>class="current"<% end %>>
            <%= link_name %>
            <% count = @interpretation.formulations_with_local(agent_locale).count%>
            <span class="badge" data-count="<%= count %>" <% if @current_locale == agent_locale %>id="current-locale-tab-badge"<% end %>>
              <%= count %>
            </span>
          </a>
        </li>
      <% end %>
      <% if current_user.can? :edit, @agent %>
        <% if @agent.locales.count != Locales::ALL.count %>
          <li>
            <a href="<%= user_agent_interpretation_select_new_locale_path(@agent.owner, @agent, @interpretation) %>"
                data-action="open-remote-modal">
              +
            </a>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>

  <% if current_user.can? :edit, @agent %>
    <%= render partial: 'formulations/form', locals: {
      agent: @agent,
      interpretation: @interpretation,
      formulation: @formulation,
      current_locale: @current_locale
    } %>
  <% end %>
</div>

<%= render partial: '/formulations/formulations_list', locals: {
    agent: @agent,
    interpretation: @interpretation,
    current_locale: @current_locale
} %>

<%= render partial: 'formulations/blankslate_start', locals: {
    agent: @agent,
    interpretation: @interpretation,
    current_locale: @current_locale
} %>

<% if current_user.can? :edit, @agent %>
  <div class="popup-overlay" id="popup-add-tag-overlay" style="display:none;"></div>
  <div class="popup-highlight" id="highlight" style="display:none;"></div>
  <div class="popup" id="popup-add-tag" style="display:none;">
    <div class="popup__search">
      <input type="text" value="" placeholder="<%= t('views.formulations.popup.add-tag.search_placeholder') %>" />
    </div>
    <ul>
      <% @agent.reachable_interpretations(@interpretation).each do |interpretation| %>
        <li data-search="<%= interpretation.slug %>" class="enabled">
          <a href="#" data-action="add-tag"
             data-data='<%= interpretation_to_json(interpretation) %>'><%= interpretation.slug %></a>
        </li>
      <% end %>
      <% @agent.reachable_entities_lists.each do |elist| %>
        <li data-search="<%= elist.slug %>" class="enabled">
          <a href="#" data-action="add-tag"
             data-data='<%= entities_list_to_json(elist) %>'><%= elist.slug %></a>
        </li>
      <% end %>
      <li data-search="number" class="enabled">
        <a href="#" data-action="add-tag"
           data-data='<%= number_to_json() %>'> <%= t('views.formulations.number') %></a>
      </li>
      <li data-search="regex" class="enabled">
        <a href="#" data-action="add-tag"
           data-data='<%= regex_to_json() %>'> <%= t('views.formulations.regex') %></a>
      </li>
    </ul>
  </div>

  <div class="popup-overlay" id="popup-remove-tag-overlay" style="display:none;"></div>
  <div class="popup" id="popup-remove-tag" style="display:none;">
    <ul>
      <li class="enabled">
        <a href="#" data-action="remove-tags">
          <span class="icon icon--small">
            <%= icon_close %>
          </span>
          <%= t('views.formulations.popup.remove-tags.msg') %>
        </a>
      </li>
    </ul>
  </div>
<% end %>

webapp/app/views/formulations/_show.js.erb
$("#formulation-<%= @formulation.id %>").replaceWith("<%= escape_javascript(@show) %>");
App.CardListHelper.updateDraggable();

webapp/app/views/formulations/_show_detailed.js.erb
App.CardListHelper.showItemDetails("#formulation-<%= @formulation.id %>", "<%= escape_javascript(@show) %>");
App.CodeEditor.buildJavaScriptEditor($("#solution__<%= @formulation.id %>")[0], true);

$("body").trigger('formulations:show-detailed:complete');

webapp/app/views/formulations/_update_failed.js.erb
$("#formulation-<%= @formulation.id %>").html("<%= escape_javascript(@form) %>");

webapp/app/views/formulations/_update_succeed.js.erb
$("#formulation-<%= @formulation.id %>").replaceWith("<%= escape_javascript(@show) %>");
App.CardListHelper.updateDraggable();