webapp/config/routes.rb
class FeatureChatbotConstraint
  def matches?(request)
    u = User.current_user_through_cookies(request.cookie_jar)
    if u.nil?
      Feature.chatbot_enabled?
    else
      Feature.chatbot_enabled? && u.chatbot_enabled
    end
  end
end


Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'backend/invitations', registrations: 'registrations'
  }

  namespace :backend do
    resources :users, only: [:index, :destroy] do
      member do
        get :confirm_destroy
        get :reinvite
        post :toggle_quota_enabled
        post :toggle_chatbot_enabled
      end
      post :impersonate, on: :member
    end
    get 'dashboard', to: 'dashboard#index'
  end

  resource :profile, only: [:show, :edit, :update, :destroy] do
    get :confirm_destroy
    post :stop_impersonating, on: :collection
  end

  resources :chatbots, only: [:index, :show], constraints: FeatureChatbotConstraint.new do
    collection do
      get :search
    end
    member do
      get :reset
    end
    resources :chat_statements, only: [:index, :create] do
      collection do
        post :user_action
      end
    end
  end

  namespace :play do
    resource :selection, only: [:edit, :update] do
      collection do
        get :search
      end
    end
  end
  get  '/play', to: 'play#index'
  post '/play', to: 'play#interpret'
  get  '/play/reset', to: 'play#reset'

  scope '/agents' do
    resources :favorites, only: [:create, :destroy]
    resources :users, path: '', only: [] do
      resources :agents, path: '', except: [:index] do
        member do
          get :confirm_destroy
          get :confirm_transfer_ownership
          post :transfer_ownership
          post :duplicate
          get :generate_token
          get :interpret, to: 'console#interpret'
          get :full_export, to: 'agents_exports#full_export'
          get :agents_selection, to: 'agents_selection#index'
        end

        resources :memberships, only: [:index, :new, :create, :update, :destroy] do
          get :confirm_destroy
        end

        resources :dependencies, only: [:new, :create, :destroy] do
          get :confirm_destroy
          collection do
            get :successors_graph
            get :predecessors_graph
          end
        end

        resource :readme, except: [:show] do
          get :confirm_destroy
        end

        resources :interpretations, path: 'interpretations' do
          member do
            post :move_to_agent
          end

          get :select_new_locale
          post :add_locale
          get :confirm_destroy

          collection do
            post :update_positions
          end

          resources :aliased_interpretations, only: :index

          resources :formulations, only: [:show, :create, :edit, :update, :destroy] do
            member do
              get :show_detailed
              post :update_locale
            end
            collection do
              post :update_positions
            end
          end
        end

        resources :entities_lists do
          member do
            post :move_to_agent
            get :export, to: 'entities_lists_exports#show'
          end

          get :confirm_destroy

          collection do
            post :update_positions
          end

          resources :aliased_interpretations, only: :index

          resources :entities, only: [:show, :create, :edit, :update, :destroy] do
            member do
              get :show_detailed
            end
            collection do
              post :update_positions
              get :new_import
              post :create_import
            end
          end
        end

        resources :agent_regression_checks, only: [:create, :update, :destroy] do
          collection do
            post :run
            post :update_positions
          end
        end

        resources :bots, except: [:show], constraints: FeatureChatbotConstraint.new do
          member do
            get :confirm_destroy
          end
          collection do
            get :ping
          end
        end

      end
    end
  end

  get 'agents', to: 'agents#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    # disable ip_spoofing, because it does not support multiple reverse proxy with different configuration (HTTP_X_REAL_IP != HTTP_X_FORWARDED_FOR)
    Sidekiq::Web.use(Rack::Protection, except: :ip_spoofing)

    mount Sidekiq::Web => '/backend/jobs'
  end

  # API with versioning
  namespace :api do
    namespace :v1 do
      scope '/agents' do
        get '/:ownername/:agentname/interpret', to: 'nlp#interpret'
      end
      get '/ping', to: 'ping#ping'
      resources 'chat_sessions', only: [:update], constraints: FeatureChatbotConstraint.new do
        resources 'statements', only: [:create], controller: 'chat_statements'
      end
    end
  end

  # API internal without versioning
  namespace :api_internal do
    get '/packages',              to: 'packages#index'
    get '/packages/:id',          to: 'packages#show'
    post '/packages/:id/updated', to: 'packages#updated'
  end

  get 'style-guide(/:page_id)', to: "style_guide#page"

  unless File.exist? File.join(Rails.root, 'public', 'index.html')
    devise_scope :user do
      unauthenticated :user do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
      authenticate :user do
        root to: 'agents#index', as: :authenticated_root
      end
    end
  end

  get "connexion_state" => "application#connexion_state"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_error", via: :all
end

webapp/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile

  def show
    @top_agents_by_expressions_count = @profile
      .agents_by_expressions_count
      .page(params[:expressions_page])
      .per(10)

    @to = DateTime.now
    @from = (DateTime.now - 30.days).beginning_of_day

    @requests_count = InterpretRequestReporter.new
      .with_owner(@profile.id)
      .between(@from, @to)
      .from_api
      .count

    if Feature.quota_enabled? && @profile.quota_enabled
      @requests_under_count = InterpretRequestReporter.new
        .with_owner(@profile.id)
        .between(@from, @to)
        .under_quota
        .count

      @requests_over_count = InterpretRequestReporter.new
        .with_owner(@profile.id)
        .between(@from, @to)
        .over_quota
        .count

      @processed_requests_over_time = InterpretRequestReporter.new
        .with_owner(@profile.id)
        .between(@from, @to)
        .under_quota
        .count_per_hours

      @rejected_requests_over_time = InterpretRequestReporter.new
        .with_owner(@profile.id)
        .between(@from, @to)
        .over_quota
        .count_per_hours

      @heapmap_under = InterpretRequestReporter.new
        .with_owner(@profile.id)
        .between(@from, @to)
        .under_quota
        .count_per_agent_and_per_day

      @heapmap_over = InterpretRequestReporter.new
        .with_owner(@profile.id)
        .between(@from, @to)
        .over_quota
        .count_per_agent_and_per_day

    else
      @api_requests_over_time = InterpretRequestReporter.new
        .with_owner(@profile.id)
        .between(@from, @to)
        .from_api
        .count_per_hours

      @api_heapmap = InterpretRequestReporter.new
        .with_owner(@profile.id)
        .between(@from, @to)
        .from_api
        .count_per_agent_and_per_day
    end
  end

  def edit
  end

  def update
    password = user_params[:password]

    if password.blank?
      data = user_without_password_params
    elsif @profile.valid_password? password
      data = user_without_password_params
    else
      data = user_params
    end

    if @profile.update(data)
      bypass_sign_in(@profile)
      redirect_to edit_profile_path
    else
      render 'edit'
    end
  end

  def confirm_destroy
    render partial: 'confirm_destroy', locals: { profile: @profile }
  end

  def destroy
    if @profile.destroy
      redirect_to new_user_session_path, notice: t('views.profile.confirm_destroy.success_message')
    else
      redirect_to edit_profile_path, alert: t(
        'views.profile.confirm_destroy.errors_message',
        errors: @profile.errors.full_messages.join(', ')
      )
    end
  end

  def stop_impersonating
    stop_impersonating_user
    cookies.delete :impersonated_user_id # Needed for ActionCable
    redirect_to agents_path, notice: t('views.profile.stop_switch.success_message')
  end


  private

    def set_profile
      @profile = current_user
    end

    def user_params
      params.require(:profile).permit(:email, :password, :name, :username, :bio, :image, :remove_image)
    end

    def user_without_password_params
      params.require(:profile).permit(:email, :name, :username, :bio, :image, :remove_image)
    end
end

webapp/app/views/profiles/_confirm_destroy.html.erb
<div class="modal" style="display: none;">
  <div class="modal__overlay" data-action='close-modal'></div>
  <div class="modal__main">
    <h5 class="modal__main__title">
      <%= t('views.profile.confirm_destroy.title') %>
      <button class="modal__main__title__close" data-action='close-modal'>
        <%= icon_close %>
      </button>
    </h5>
    <div class="modal__main__content">
      <p>
        <%= t('views.profile.confirm_destroy.message') %>
      </p>
      <%= form_for(profile, url: profile_path, method: :delete, html: { data: { validation: :delete }}) do |f| %>
        <div class="field">
          <div class="control">
            <label><%= t('confirm_destroy.label') %></label>
            <div>
              <input type="text" name="validation" />
            </div>
            <div class="help help--error" style="display:none;">
              <span class="icon icon--x-small"><%= icon_alert %></span>
              <%= t('confirm_destroy.error') %>
            </div>
          </div>
        </div>
        <%= f.button t('views.profile.confirm_destroy.btn'), class: "btn btn--destructive" %>
        <a href="#" class="btn btn--flat" data-action='close-modal'><%= t('cancel') %></a>
      <% end %>
    </div>
  </div>
</div>

webapp/app/views/profiles/_edit_auth.html.erb
<%= form_for(@profile, as: :profile, url: profile_path, html: { method: :put }) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.label :email %>
      &nbsp;<span class="badge badge--small badge--outline"><%= t('required') %></span>
      <br />
      <%= f.text_field :email, autocomplete: "off" %>
      <%= display_errors(@profile, :email) %>

      <% if Feature.email_configured? && @profile.pending_reconfirmation? %>
        <div class="help help--success">
          <span class="icon icon--x-small"><%= icon_information %></span>
          <%= t('views.profile.edit.authentication.waiting_email_confirmation', email: @profile.unconfirmed_email) %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :password %>
      <span class="help">
        <span class="icon icon--x-small"><%= icon_information %></span>
        <%= t('views.profile.edit.authentication.password_constraint', min_length: User.password_length.min) %>
      </span>

      <br />
      <%= f.password_field :password, autocomplete: "off" %>
      <%= display_errors(@profile, :password) %>

      <div class="help">
        <span class="icon icon--x-small"><%= icon_information %></span>
        <%= t('views.profile.edit.authentication.leave_blank') %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.button t('views.profile.edit.authentication.submit_btn'), class: "btn btn--primary",
        data: {
          disable_with: "<span class='icon icon--spin'>#{icon_loading}</span> #{t('loading')}".html_safe
        } %>
    <a href="<%= profile_path %>" class="btn btn--plain">Cancel</a>
  </div>
<% end %>

webapp/app/views/profiles/_edit_avatar.html.erb
<%= form_for(@profile, as: :profile, url: profile_path, html: { method: :put }) do |f| %>
  <div class="profile-edit-avatar">
    <div>
      <div class="avatar avatar--large">
        <img src="<%= @profile.image_url(:square) %>">
      </div>
      <% unless @profile.image.nil? %>
        <%= f.check_box :remove_image %>
        <label for="profile_remove_image">Remove</label>
      <% end %>
    </div>
    <div>
      <p class="field__title">Upload new avatar</p>
      <div class="field field--upload">
        <%= f.hidden_field :image, value: @profile.cached_image_data %>
        <label for="upload_image">
          <div>
            <p>
              <%= t('file_upload_label') %>
            </p>
            <div class="help">
              <span class="icon icon--x-small"><%= icon_information %></span>
               The maximum file size allowed is 2Mo.
            </div>
            <%= display_errors(@profile, :image) %>
          </div>
        </label>
        <%= f.file_field :image, id: 'upload_image' %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.button t('views.profile.edit.global.submit_btn'), class: "btn btn--primary",
        data: {
          disable_with: "<span class='icon icon--spin'>#{icon_loading}</span> #{t('loading')}".html_safe
        } %>
    <a href="<%= profile_path %>" class="btn btn--plain">Cancel</a>
  </div>
<% end %>

webapp/app/views/profiles/_edit_destroy.html.erb
<% if @profile.can_be_destroyed? %>
  <p><%= t('views.profile.edit.destroy.message') %></p>
  <p>
    <a href="<%= confirm_destroy_profile_path %>"
       class="btn btn--destructive"
       data-action="open-remote-modal">
      <%= t('views.profile.edit.destroy.btn') %>
    </a>
  </p>
<% else %>
  <div class="note note--warning">
    <div class="note__icon icon--small">
      <span class="icon icon--small"><%= icon_alert %></span>
    </div>
    <div class="note__content">
      <%= t('views.profile.edit.destroy.not_possible_message') %>
    </div>
  </div>
<% end %>

webapp/app/views/profiles/_edit_global.html.erb
<%= form_for(@profile, as: :profile, url: profile_path, html: { method: :put }) do |f| %>

  <div class="field">
    <div class="control">
      <%= f.label :name %><br />
      <%= f.text_field :name, placeholder: "John Smith" %>
      <%= display_errors(@profile, :name) %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.label :username %>
      &nbsp;<span class="badge badge--small badge--outline"><%= t('required') %></span>
      <br />
      <%= f.text_field :username, placeholder: "jsmith" %>
      <%= display_errors(@profile, :username) %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.label :bio %><br />
      <%= f.text_area :bio, placeholder: "Tell us a little about yourself" %>
      <%= display_errors(@profile, :bio) %>
    </div>
  </div>
  <div class="field">
    <%= f.button t('views.profile.edit.global.submit_btn'), class: "btn btn--primary",
        data: {
          disable_with: "<span class='icon icon--spin'>#{icon_loading}</span> #{t('loading')}".html_safe
        } %>
    <a href="<%= profile_path %>" class="btn btn--plain">Cancel</a>
  </div>

  <% if Feature.privacy_policy_enabled? %>
    <div class="note">
      <div class="note__icon">
        <span class="icon icon--small"><%= icon_information %></span>
      </div>
      <div class="note__content">
        <%= t('views.profile.edit.legal_html',
              privacy_policy_url: ENV['VIKYAPP_PRIVACY_POLICY_URL']
            ) %>
      </div>
    </div>
  <% end %>

<% end %>

webapp/app/views/profiles/_show_api_usage.html.erb
<%
if Feature.quota_enabled? && @profile.quota_enabled
  quota = Quota.max_interpret_requests_per_day * 30
  percentage = (@requests_count * 100 / quota)
end
%>

<div class="card" style="z-index: 1;position: relative;">
  <div class="card-content card-content--profile">

    <div class="profile-dashboard">

      <div class="profile-radial">
        <div>
          <% if Feature.quota_enabled? && @profile.quota_enabled %>
            <div class="graph-radial"
                 data-series="<%= [percentage].to_json %>"
                 data-labels="<%= [t('views.profile.show_api_use.radial_graph_label')].to_json %>"
                 data-colors="<%= ['#3bb8d7'].to_json %>">
            </div>
          <% else %>
            <div class="graph-radial-unlimited">
              <div>
                <span class="icon icon--large icon--grey">
                  <%= icon_information %>
                </span>
                <br />
                <%= t('views.profile.show_api_use.unlimited_html') %>
              </div>
            </div>
          <% end %>
        </div>

        <div>
          <div class="profile-radial-data">

            <div class="indicator profile-radial-data__primary">
              <span class="indicator-number">
                <strong><%= number_with_delimiter(@requests_count) %></strong>
                <% if Feature.quota_enabled? && @profile.quota_enabled %>
                  <small>/<%= number_with_delimiter(quota) %></small>
                <% end %>
              </span>
              <%= t('views.profile.show_api_use.all_requests') %>
            </div>

            <% if Feature.quota_enabled? && @profile.quota_enabled %>
              <div class="indicator indicator--secondary profile-radial-data__secondary-1">
                <span class="indicator-number">
                  <strong><%= number_with_delimiter(@requests_under_count) %></strong>
                </span>
                <%= t('views.profile.show_api_use.under_quota_requests') %>
              </div>
              <div class="indicator indicator--secondary profile-radial-data__secondary-2">
                <span class="indicator-number">
                  <strong><%= number_with_delimiter(@requests_over_count) %></strong>
                </span>
                <%= t('views.profile.show_api_use.over_quota_requests') %>
              </div>
            <% end %>

          </div>
        </div>

      </div>


      <% if Feature.quota_enabled? && @profile.quota_enabled %>
        <div class="profile-dashboard__on-right">
          <h5><%= t('views.profile.show_api_use.quota.title') %></h5>
          <p class="profile-dashboard-note">
            <span class="icon icon--small icon--grey">
              <%= icon_information %>
            </span>
            <%= t('views.profile.show_api_use.quota.help') %>
          </p>
          <div class="profile-api-quota">
            <div class="indicator indicator--secondary">
              <span class="indicator-number">
                <strong><%= number_with_delimiter(Quota.max_interpret_requests_per_day) %></strong>
              </span>
              <%= t('views.profile.show_api_use.quota.per_day') %>
            </div>
            <div class="indicator indicator--secondary">
              <span class="indicator-number">
                <strong><%= number_with_delimiter(Quota.max_interpret_requests_per_second) %></strong>
              </span>
              <%= t('views.profile.show_api_use.quota.per_second') %>
            </div>
          </div>
        </div>
      <% end %>

    </div>

  </div>
</div>


<% if @requests_count > 0 %>
  <div class="profile-api-detail">

    <div>
      <h5><%= t('views.profile.show_api_use.request_distribution.title') %></h5>
      <% if Feature.quota_enabled? && @profile.quota_enabled %>
        <div class="graph-area"
             data-series='<%= build_area_graph_data_with_quota(
               @processed_requests_over_time,
               @rejected_requests_over_time,
             ).to_json %>'></div>
      <% else %>
        <div class="graph-area"
             data-series='<%= build_area_graph_data_without_quota(
               @api_requests_over_time
             ).to_json %>'></div>
      <% end %>
    </div>

    <div>
      <% if Feature.quota_enabled? && @profile.quota_enabled %>
        <h5><%= t('views.profile.show_api_use.heapmap_under.title') %></h5>
        <div class="graph-heatmap"
             data-series="<%= build_heatmap_data(@heapmap_under).to_json %>"
             data-color="#3bb8d7"></div>

        <% over_quota_distribution = build_heatmap_data(@heapmap_over) %>
        <% if over_quota_distribution.size > 0 %>
          <h5><%= t('views.profile.show_api_use.heapmap_over.title') %></h5>
          <div class="graph-heatmap"
               data-series="<%= over_quota_distribution.to_json %>"
               data-color="#ff3860"></div>
        <% end %>
      <% else %>
        <h5><%= t('views.profile.show_api_use.heapmap_under.title_without_quota') %></h5>
        <div class="graph-heatmap"
             data-series="<%= build_heatmap_data(@api_heapmap).to_json %>"
             data-color="#3bb8d7"></div>
      <% end %>
    </div>

  </div>
<% end %>

webapp/app/views/profiles/_show_data_usage.html.erb
<%
expressions_count = @profile.expressions_count
entities_count = @profile.entities_count
formulations_count = @profile.formulations_count
if Feature.quota_enabled? && @profile.quota_enabled
  expressions_quota = Quota.expressions_limit
  percentage = (expressions_count.to_f * 100 / expressions_quota).round(1)
end
%>

<div class="profile-dashboard">
  <div>

    <div class="profile-radial">
      <div>
        <% if Feature.quota_enabled? && @profile.quota_enabled %>
          <div class="graph-radial"
               data-series="<%= [percentage].to_json %>"
               data-labels="<%= [t('views.profile.show_data_use.radial_graph_label')].to_json %>"
               data-colors="<%= ['#3bb8d7'].to_json %>">
          </div>
        <% else %>
          <div class="graph-radial-unlimited">
            <div>
              <span class="icon icon--large icon--grey">
                <%= icon_information %>
              </span>
              <br />
              <%= t('views.profile.show_data_use.unlimited_html') %>
            </div>
          </div>
        <% end %>
      </div>
      <div>
        <div class="profile-radial-data">
          <div class="indicator profile-radial-data__primary">
            <span class="indicator-number">
              <strong><%= number_with_delimiter(expressions_count) %></strong>
              <% if Feature.quota_enabled? && @profile.quota_enabled %>
              <small>/<%= number_with_delimiter(expressions_quota) %></small>
              <% end %>
            </span>
            <%= t('views.profile.show_data_use.expressions_label') %>
          </div>
          <div class="indicator indicator--secondary profile-radial-data__secondary-1">
            <span class="indicator-number">
              <strong><%= number_with_delimiter(entities_count) %></strong>
            </span>
            <%= t('views.profile.show_data_use.entities_label') %>
          </div>
          <div class="indicator indicator--secondary profile-radial-data__secondary-2">
            <span class="indicator-number">
              <strong><%= number_with_delimiter(formulations_count) %></strong>
            </span>
            <%= t('views.profile.show_data_use.formulations_label') %>
          </div>
        </div>
      </div>
    </div>

  </div>

  <% if @top_agents_by_expressions_count.size > 0 %>
    <div class="profile-dashboard__on-right profile-expressions-top-agents">
      <h5>
        <%= t('views.profile.show_data_use.top.title') %>
        <%= link_to_previous_page @top_agents_by_expressions_count, t('views.profile.show_data_use.top.previous'), param_name: :expressions_page, class: 'btn btn--small btn--outline' %>
        <%= link_to_next_page @top_agents_by_expressions_count, t('views.profile.show_data_use.top.next'), param_name: :expressions_page, class: 'btn btn--small btn--outline' %>
      </h5>
      <ol <% if @top_agents_by_expressions_count.size > 5 %>class="two-columns"<% end %>>
        <% @top_agents_by_expressions_count.each do |e|%>
          <% agent = Agent.find(e.id) %>
          <li>
            <span><%= number_with_delimiter e.total %></span>
            <a href="<%= user_agent_path(agent.owner, agent)%>">
              <%= agent.name %>
            </a>
          </li>
        <% end %>
      </ol>
    </div>
  <% end %>

</div>

webapp/app/views/profiles/_show_user.html.erb
<div class="profile-show">

  <div class="avatar avatar--large">
    <img src="<%= @profile.image_url(:square) %>">
  </div>

  <div>
    <div class="profile-show__data">
      <div>
        <p>
          <span class="profile-show__label">
            <%= t('activerecord.attributes.user.name') %>
          </span>
          <% if @profile.name.blank? %>
            <span class="profile-show__missing">
              <%= t('views.profile.show_user.missing_info') %>
            </span>
          <% else %>
            <%= @profile.name %>
          <% end %>
        </p>
        <p>
          <span class="profile-show__label">
            <%= t('activerecord.attributes.user.username') %>
          </span>
          <% if @profile.username.blank? %>
            <span class="profile-show__missing">
              <%= t('views.profile.show_user.missing_info') %>
            </span>
          <% else %>
            <%= @profile.username %>
          <% end %>
        </p>
      </div>
      <div>
        <p>
          <span class="profile-show__label">
            <%= t('activerecord.attributes.user.email') %>
          </span>
          <%= @profile.email %>
        </p>
        <p>
          <span class="profile-show__label">
            <%= t('activerecord.attributes.user.bio') %>
          </span>
          <% if @profile.bio.blank? %>
            <span class="profile-show__missing">
              <%= t('views.profile.show_user.missing_info') %>
            </span>
          <% else %>
            <%= @profile.bio %>
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <div>
    <a href="<%= edit_profile_path %>" class="btn btn--small btn--primary">
      <span class="icon icon--x-small"><%= icon_edit %></span> <%= t('views.profile.show_user.edit_btn') %>
    </a>
  </div>
</div>

webapp/app/views/profiles/edit.html.erb
<div class="profile">

  <header class="header">
    <div class="header__breadcrumb">
      <%= link_to t('views.profile.breadcrumb'), profile_path %> /
      <strong><%= t('views.profile.edit.breadcrumb') %></strong>
    </div>
  </header>

  <div class="profile-edit-global-avatar">
    <div>
      <h4><%= t('views.profile.edit.global.title') %></h4>
      <div class="card">
        <div class="card-content test-profile-edit-global">
          <%= render 'edit_global' %>
        </div>
      </div>
    </div>
    <div>
      <h4><%= t('views.profile.edit.avatar.title') %></h4>
      <div class="card">
        <div class="card-content test-profile-edit-avatar">
          <%= render 'edit_avatar' %>
        </div>
      </div>
    </div>
  </div>

  <div class="profile-edit-auth-destroy">
    <div>
      <h4><%= t('views.profile.edit.authentication.title') %></h4>
      <div class="card">
        <div class="card-content test-profile-edit-auth">
          <%= render 'edit_auth' %>
        </div>
      </div>
    </div>
    <div>
      <h4><%= t('views.profile.edit.destroy.title') %></h4>
      <div class="card">
        <div class="card-content test-profile-edit-destroy">
          <%= render 'edit_destroy' %>
        </div>
      </div>
    </div>
  </div>

</div>

webapp/app/views/profiles/show.html.erb
<div class="profile">

  <h4><%= t('views.profile.show_user.title') %></h4>
  <div class="card">
    <div class="card-content">
      <%= render 'show_user' %>
    </div>
  </div>

  <h4><%= t('views.profile.show_data_use.title') %></h4>
  <div class="card">
    <div class="card-content card-content--profile">
      <%= render 'show_data_usage' %>
    </div>
  </div>

  <h4><%= t('views.profile.show_api_use.title') %></h4>
  <%= render 'show_api_usage' %>
</div>